name: CI

run-name: ${{ github.event.pull_request.merged && github.event.pull_request.title || (github.event_name == 'push' && 'CI (All) with deployment to dev') || 'CI ' + (inputs.apps == '' && 'All' || join(fromJson(inputs.apps), ',')) + (inputs['deploy-to-dev'] && ' with deployment to dev' || ' without deployment to dev') }}


on: 
  workflow_dispatch:
    inputs:
      apps:
        description: 'apps'
        default: '["app1","app2"]'
        type: string
      deploy-to-dev:
        description: 'deploy-to-dev'
        default: true
        type: boolean
  push:


jobs:
  
  set-env-var:
    name: set up
    runs-on: ubuntu-latest
    steps:
      - name: echo statement
        shell: bash
        run: |
          echo "hi, how do you do"
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event_name }}
  
    
        
