name: CI

run-name: >
run-name: >
  ${{ 
    github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.title ||
    (github.event_name == 'push' && 'CI (All) with deployment to dev') ||
    (github.event_name == 'workflow_dispatch' && (
      inputs.apps == '' && 
        format('CI (All){}', inputs['deploy-to-dev'] == 'true' && ' with deployment to dev' || ' without deployment to dev') ||
      inputs.apps != '' &&
        format('CI ({}){}', join(fromJson(inputs.apps), ','), inputs['deploy-to-dev'] == 'true' && ' with deployment to dev' || ' without deployment to dev')
    ))
  }}
  
on: 
  workflow_dispatch:
    inputs:
      apps:
        description: 'apps'
        default: '["app1","app2"]'
        type: string
      deploy-to-dev:
        description: 'deploy-to-dev'
        default: true
        type: boolean
  push:


jobs:
  
  set-env-var:
    name: set up
    runs-on: ubuntu-latest
    steps:
      - name: echo statement
        shell: bash
        run: |
          echo "hi, how do you do"
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event_name }}
  
    
        
